name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Create JKS File
        run: |
          keytool -genkey -v -keystore gomini.jks -alias gomini-key -keyalg RSA -keysize 2048 -validity 10000 -storepass "MyStrongPass123!#" -keypass "MyStrongPass123!#" -dname "CN=Gomini, OU=App, O=Gomini, L=Tehran, S=Tehran, C=IR"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gomini-keystore
          path: gomini.jks
